version: '3'

services:
  mysql:
    image: 'mysql/mysql-server:8.0'
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    healthcheck:
      test:
          - CMD
          - mysqladmin
          - ping
          - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s

  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
