---
openapi: 3.0.0
info:
  title: Pet Shop API - Swagger Documentation
  description: ''
  contact:
    name: Lemuel Flores
    email: is101.lemuel@gmail.com
  version: 1.0.0
servers: []
paths:
  "/api/v1/order-status/{uuid}":
    get:
      tags:
      - Order Statuses
      summary: Fetch an order status
      operationId: order-statuses-read
      parameters:
      - name: uuid
        required: true
        in: path
        schema:
          type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      security: []
  "/api/v1/order-statuses":
    get:
      tags:
      - Order Statuses
      summary: List all order statuses
      operationId: order-statuses-listing
      parameters:
      - name: page
        required: false
        in: query
        schema:
          type: integer
      - name: limit
        required: false
        in: query
        schema:
          type: integer
      - name: sortBy
        required: false
        in: query
        schema:
          type: string
      - name: desc
        required: false
        in: query
        schema:
          type: boolean
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      security: []

  "/api/v1/user":
    get:
      tags:
      - User
      summary: View a User account
      operationId: user-read
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  "/api/v1/user/orders":
    get:
      tags:
      - User
      summary: List all orders for the user
      operationId: user-orders-listing
      parameters:
      - name: page
        required: false
        in: query
        schema:
          type: integer
      - name: limit
        required: false
        in: query
        schema:
          type: integer
      - name: sortBy
        required: false
        in: query
        schema:
          type: string
      - name: desc
        required: false
        in: query
        schema:
          type: boolean
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  "/api/v1/user/login":
    post:
      tags:
      - User
      summary: Login an User account
      operationId: user-login
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
              - email
              - password
              properties:
                email:
                  type: string
                  description: User email
                password:
                  type: string
                  description: User password
              type: object
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '404':
          description: Page not found
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal server error
      security: []
  "/api/v1/user/create":
    post:
      tags:
      - User
      summary: Create a User account
      operationId: user-create
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
              - first_name
              - last_name
              - email
              - password
              - password_confirmation
              - address
              - phone_number
              properties:
                first_name:
                  type: string
                  description: User firstname
                last_name:
                  type: string
                  description: User lastname
                email:
                  type: string
                  description: User email
                password:
                  type: string
                  description: User password
                password_confirmation:
                  type: string
                  description: User password
                avatar:
                  type: string
                  description: Avatar image UUID
                address:
                  type: string
                  description: User main address
                phone_number:
                  type: string
                  description: User main phone number
                is_marketing:
                  type: string
                  description: User marketing preferences
              type: object
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '404':
          description: Page not found
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal server error
      security: []

  "/api/v1/file/upload":
    post:
      tags:
      - File
      summary: Upload a file
      operationId: file-upload
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              required:
              - file
              properties:
                file:
                  type: string
                  format: binary
                  description: file to upload
              type: object
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '404':
          description: Page not found
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal server error
  "/api/v1/file/{uuid}":
    get:
      tags:
      - File
      summary: Read a file
      operationId: file-read
      parameters:
      - name: uuid
        required: true
        in: path
        schema:
          type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '404':
          description: Page not found
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal server error
      security: []

  "/api/v1/admin/login":
    post:
      tags:
      - Admin
      summary: Login an Admin account
      operationId: admin-login
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
              - email
              - password
              properties:
                email:
                  type: string
                  description: Admin email
                password:
                  type: string
                  description: Admin password
              type: object
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '404':
          description: Page not found
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal server error
      security: []
  "/api/v1/admin/create":
    post:
      tags:
      - Admin
      summary: Create an Admin account
      operationId: admin-create
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
              - first_name
              - last_name
              - email
              - password
              - password_confirmation
              - address
              - phone_number
              properties:
                first_name:
                  type: string
                  description: User firstname
                last_name:
                  type: string
                  description: User lastname
                email:
                  type: string
                  description: User email
                password:
                  type: string
                  description: User password
                password_confirmation:
                  type: string
                  description: User password
                avatar:
                  type: string
                  description: Avatar image UUID
                address:
                  type: string
                  description: User main address
                phone_number:
                  type: string
                  description: User main phone number
                marketing:
                  type: string
                  description: User marketing preferences
              type: object
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '404':
          description: Page not found
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal server error
      security: []

  "/api/v1/main/promotions":
    get:
      tags:
      - MainPage
      summary: List all promotions
      operationId: mainpage-promotions
      parameters:
      - name: page
        required: false
        in: query
        schema:
          type: integer
      - name: limit
        required: false
        in: query
        schema:
          type: integer
      - name: sortBy
        required: false
        in: query
        schema:
          type: string
      - name: desc
        required: false
        in: query
        schema:
          type: boolean
      - name: valid
        required: false
        in: query
        schema:
          type: boolean
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '404':
          description: Page not found
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal server error
      security: []
  "/api/v1/main/blog":
    get:
      tags:
      - MainPage
      summary: List all posts
      operationId: mainpage-posts
      parameters:
      - name: page
        required: false
        in: query
        schema:
          type: integer
      - name: limit
        required: false
        in: query
        schema:
          type: integer
      - name: sortBy
        required: false
        in: query
        schema:
          type: string
      - name: desc
        required: false
        in: query
        schema:
          type: boolean
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '404':
          description: Page not found
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal server error
      security: []
  "/api/v1/main/blog/{uuid}":
    get:
      tags:
      - MainPage
      summary: Fetch a post
      operationId: mainpage-post
      parameters:
      - name: uuid
        required: true
        in: path
        schema:
          type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '404':
          description: Page not found
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal server error
      security: []

  "/api/v1/exchange":
    get:
      tags:
      - Exchange
      summary: Exchange EUR to another currency
      operationId: exchange-get
      parameters:
      - name: amount
        required: true
        in: query
        schema:
          type: number
      - name: currency
        required: true
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal server error
      security: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      name: bearerAuth
      in: header
      bearerFormat: JWT
      scheme: bearer
tags:
- name: Admin
  description: Admin API endpoint
- name: User
  description: User API endpoint
- name: MainPage
  description: MainPage API endpoint
- name: Order Statuses
  description: Order statuses API endpoint
- name: File
  description: File API endpoint
- name: Exchange
  description: Exchange API endpoint
security:
- bearerAuth: []
