name: "Run Tests"

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: lorisleiva/laravel-docker:8.2

    services:
      mysql:
        image: 'mysql:8.0'
        env:
          MYSQL_DATABASE: 'testing'
          MYSQL_USER: 'username'
          MYSQL_PASSWORD: 'password'
          MYSQL_ROOT_PASSWORD: 'password'
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Install composer dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Prepare Laravel application
        run: cp .env.example .env.testing

      - name: Run tests
        run: php artisan test

      - name: PHP Insights
        run: php artisan insights --no-interaction

      - name: PHPStan
        run: vendor/bin/phpstan analyse || true
